name: backfill_scores
on:
  workflow_dispatch:
    inputs:
      year:
        description: "Season year"
        required: true
        default: "2024"

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip nfl_data_py pandas
      - run: python scripts/backfill_scores_to_odds.py --year "${{ inputs.year }}"
      - name: Commit updated odds
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git add data/archive/season=${{ inputs.year }}/odds.csv
          git commit -m "chore(archive): backfill scores into odds for season ${{ inputs.year }}" || echo "no changes"
          git push
