name: update_odds_weekly

permissions:
  contents: write

concurrency:
  group: odds-weekly-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "5 15 * * 3"
  workflow_dispatch:
    inputs:
      season:
        description: "Override season (optional)"
        required: false
      week:
        description: "Override week (optional)"
        required: false
      archive_force:
        description: "Force archive now"
        required: false
        default: "false"
      price_factor:
        description: "Execution price factor (e.g. 1.022)"
        required: false
        default: "1.022"

jobs:
  fetch_odds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests python-dateutil pytz

      - name: Ensure folders
        run: |
          mkdir -p data/live
          mkdir -p data/archive

      - name: Debug secret presence
        run: |
          if [ -z "${{ secrets.ODDS_API_KEY }}" ]; then
            echo "ODDS_API_KEY repo secret is NOT set."
            exit 1
          fi

      - name: Debug env var mapping
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: |
          if [ -z "$ODDS_API_KEY" ]; then
            echo "ODDS_API_KEY env var is empty."
            exit 1
          fi

      - name: Fetch odds (current week) + auto-archive if season ended
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
          PF_INPUT: ${{ github.event.inputs.price_factor }}
          SEASON: ${{ github.event.inputs.season }}
          WEEK: ${{ github.event.inputs.week }}
          ARCHIVE_FORCE: ${{ github.event.inputs.archive_force }}
        run: |
          set -e
          if [ -z "$PF_INPUT" ]; then PF_INPUT="1.022"; fi
          python scripts/fetch_odds.py \
            --markets "h2h,spreads,totals" \
            --only-current-week \
            --price-factor "$PF_INPUT" \
            ${SEASON:+--season "$SEASON"} \
            ${WEEK:+--week "$WEEK"} \
            $( [ "$ARCHIVE_FORCE" = "true" ] && echo "--archive-force" )

      - name: Show live file
        run: |
          ls -lah data/live || true
          [ -f data/live/odds.csv ] && head -n 20 data/live/odds.csv || true

      - name: Upload artifact (odds-live)
        uses: actions/upload-artifact@v4
        with:
          name: odds-live-${{ github.run_id }}-${{ github.run_attempt }}
          path: data/live/odds.csv
          if-no-files-found: error

      - name: Commit & push
        run: |
          set -e
          git config user.name  "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add -f data/live/odds.csv
          git add -A data/archive || true
          git commit -m "chore(data): refresh odds live (and archive if season ended) [skip ci]" || echo "no changes"
          git push
