name: live-pregame-stats
on:
  workflow_dispatch: {}
  schedule:
    # Martes 06:35 UTC ~ Lunes 02:35 ET, después del MNF/persist
    - cron: "35 6 * * 2"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy requests pyarrow fastparquet
      - name: Build pregame stats (current season)
        env:
          TARGET_SEASON: "2025"   # opcional; quítalo para autodetectar por año ET
        run: |
          python scripts/build_live_pregame_stats.py
          echo "--- data/live ---"; ls -lah data/live || true
      - name: Commit & push
        run: |
          set -e
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore(live): update pregame YTD stats (nflverse) [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
