name: migrate-round-bets-once

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run-migration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run one-time rounding migration
        run: |
          set -euxo pipefail
          python scripts/migrate_round_bets_once.py
          echo "Preview:"
          head -n 25 data/live/bets.csv || true

      - name: Commit & push changes
        run: |
          set -e
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore(migration): round bets numeric fields to 2 decimals (one-time) [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
