name: persist-scores-pnl

on:
  workflow_dispatch: {}
  schedule:
    # TNF (Thursday Night Football)
    # Viernes 00–06 UTC  ≈ Jueves 8:00 PM–2:00 AM ET
    - cron: "*/5 0-6 * * 5"

    # Juegos internacionales del domingo (London/Frankfurt)
    # Domingo 13–16 UTC ≈ 9:00 AM–12:00 PM ET
    - cron: "*/5 13-16 * * 0"

    # Ventanas del domingo SIN huecos (1 PM y 4:05/4:25 PM ET)
    # Domingo 17–23 UTC ≈ 1:00 PM–7:59 PM ET
    - cron: "*/5 17-23 * * 0"

    # SNF (Sunday Night Football) + buffer de OT/retrasos
    # Lunes 00–05 UTC ≈ Domingo 8:00 PM–12:59 AM ET
    - cron: "*/5 0-5 * * 1"

    # MNF (Monday Night Football) + buffer
    # Martes 00–06 UTC ≈ Lunes 8:00 PM–1:59 AM ET
    - cron: "*/5 0-6 * * 2"

    # EXTRA: Lunes 23:30 UTC (último persist antes de la siguiente semana)
    - cron: "30 23 * * 1"

permissions:
  contents: write

jobs:
  persist-scores:
    name: 1) Persist finished scores into odds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests numpy

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Persist finished scores into odds
        run: |
          set -euxo pipefail
          python scripts/persist_scores.py

      - name: Commit & push (persist)
        run: |
          set -e
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore(scores): persist finished scores [skip ci]"
            git push
          else
            echo "No changes to commit (persist)."

  annotate-bets:
    name: 2) Annotate bets (profit & bankroll per week)
    runs-on: ubuntu-latest
    needs: persist-scores
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests numpy

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Annotate bets with profit & bankroll (live)
        env:
          BANKROLL_INITIAL: "1000"
        run: |
          set -euxo pipefail
          python scripts/annotate_bets_with_profit_and_bankroll.py

      - name: Commit & push (annotate)
        run: |
          set -e
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore(annotate): bets profit & bankroll (freeze finals) [skip ci]"
            git push
          else
            echo "No changes to commit (annotate)."

  build-pnl:
    name: 3) Build P&L (weekly final-only)
    runs-on: ubuntu-latest
    needs: annotate-bets
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests numpy

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Build PnL (live)
        env:
          # Anchor con el que arrancaste la season (Week 3 = $1000, por ejemplo)
          BANKROLL_INITIAL: "1000"
          # Si tus CSV viven en otra ruta, puedes sobreescribir con:
          # BPNL_BETS_CSV: "data/live/bets.csv"
          # BPNL_ODDS_CSV: "data/live/odds.csv"
        run: |
          set -euxo pipefail
          python scripts/build_pnl_live.py

      - name: Commit & push (pnl)
        run: |
          set -e
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore(pnl): build weekly P&L (final weeks only) [skip ci]"
            git push
          else
            echo "No changes to commit (pnl)."
