name: persist-scores-pnl

on:
  workflow_dispatch: {}
  schedule:
    # TNF (Thursday Night Football)
    - cron: "*/5 0-6 * * 5"
    # London/Frankfurt (domingo temprano)
    - cron: "*/5 13-16 * * 0"
    # Ventanas del domingo
    - cron: "*/5 17-23 * * 0"
    # SNF + buffer
    - cron: "*/5 0-5 * * 1"
    # MNF + buffer
    - cron: "*/5 0-6 * * 2"
    # EXTRA: Lunes 23:30 UTC
    - cron: "30 23 * * 1"

permissions:
  contents: write

jobs:
  persist-scores:
    name: 1) Persist finished scores into odds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests numpy

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Persist finished scores into odds
        run: |
          set -euxo pipefail
          python scripts/persist_scores.py

      - name: Commit & push (persist)
        run: |
          set -e
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore(scores): persist finished scores [skip ci]"
            git push
          else
            echo "No changes to commit (persist)."
          fi

  annotate-bets:
    name: 2) Annotate bets (profit & bankroll per week)
    runs-on: ubuntu-latest
    needs: persist-scores
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests numpy

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Annotate bets with profit & bankroll (live)
        env:
          BANKROLL_INITIAL: "1000"
        run: |
          set -euxo pipefail
          python scripts/annotate_bets_with_profit_and_bankroll.py

      - name: Commit & push (annotate)
        run: |
          set -e
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore(annotate): bets profit & bankroll (freeze finals) [skip ci]"
            git push
          else
            echo "No changes to commit (annotate)."
          fi

  build-pnl:
    name: 3) Build P&L (weekly final-only)
    runs-on: ubuntu-latest
    needs: annotate-bets
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests numpy

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Build PnL (live)
        env:
          BANKROLL_INITIAL: "1000"
          # BPNL_BETS_CSV / BPNL_ODDS_CSV si usas rutas custom
        run: |
          set -euxo pipefail
          python scripts/build_pnl_live.py

      - name: Commit & push (pnl)
        run: |
          set -e
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore(pnl): build weekly P&L (final weeks only) [skip ci]"
            git push
          else
            echo "No changes to commit (pnl)."
          fi
